### ISSUE TITLE
Why 'Azure HDInsight'?

### ISSUE THREAD

**Issue by analisis1data** [CreativeDataEU/PowerBITrinoConnector#17]
After placing the default 'Trino.mez' file in the appropriate Power BI folder, Power BI shows the connector as 'Azure HDInsight AKS Trino,' and for example, it only allows writing a host using an Azure URL, not a URL and port.

![trino](https://github.com/CreativeDataEU/PowerBITrinoConnector/assets/136016001/1bfc23f9-b9df-4ed8-9420-86dcb91fbeaa)

**Comment by pichlerpa** [comment]
You can use the connector (Trino.mez) as-is, you just need to follow the official way of using Power BI custom connector which is allowing extension. Or what exactly is your question?

**Comment by pichlerpa** [comment]
Closed due to inactivity.
