### ISSUE TITLE
SSL requires cert

### ISSUE THREAD

**Issue by cmeu** [CreativeDataEU/PowerBITrinoConnector#18]
With my firm's implementation, we require to specify a key file (.p12) for SSL. How can I specify that file is used when I set up this connector?

What I am really looking for is an option to enable QueryFolding. Is that implemented? The default ODBC connector doesn't let me do it.

Truly **a fantastic idea to build this**! Thank you.

**Comment by pichlerpa** [comment]
Hello @cmeu, the connector automatically uses the HTTPS connection protocol including the certificate as soon as you use an authentication method other than "anonymous", also Trino doesn't allow another constellation. QueryFolding is also not supported yet. Patrick

**Comment by pichlerpa** [comment]
Closed due to inactivity.
