### ISSUE TITLE
powerBiTrinoConnector with TLS

### ISSUE THREAD

**Issue by fcollin** [CreativeDataEU/PowerBITrinoConnector#21]
Hello,

How do you configure PowerBI to connect to a TLS secured Trino cluster ?

Regards,

**Comment by pichlerpa** [comment]
Hi @fcollin, you can simply put HTTPS as part of your hostname. Patrick

**Comment by dcp-technologies** [comment]
Hi,

It does not work. Hostname field can't contain any 'https'.
I am trying to connect Trino using the Trino mez connector in Power BI desktop.
It works with http on port 8080 but I need to need to test the connector with a secured Trino cluster (TLS + ldap authentication).

Did you manage to do it ?


Regards,

Frederic

**Comment by fcollin** [comment]
Hi,

It does not work. Hostname field can't contain any 'https'.
I am trying to connect Trino using the Trino mez connector in Power BI desktop.
It works with http on port 8080 but I need to need to test the connector with a secured Trino cluster (TLS + ldap authentication).

Did you manage to do it ?

Regards,

**Comment by pichlerpa** [comment]
Hi, 

You are right, HTTP or HTTPS is automatically added to the host name based on the authentication type used in the Power BI connector. HTTP is used for anonymous (implicit) authentication, while HTTPS is used for all other types, aligning with Trino security standards.

However, the connector has not been used with LDAP, which would be the [Windows] (https://learn.microsoft.com/en-us/power-query/handling-authentication#authentication-kinds) authentication type in Power BI Custom Connectors. Currently, it only supports Basic (UsernamePassword) and Organizational account (OAuth) authentication types.

Regards,
Patrick

**Comment by fcollin** [comment]
Thanks. Basic authentication is fine for LDAP. 
Did you try to setup a TLS connection between Power BI Desktop and Trino ?

**Comment by pichlerpa** [comment]
Yes, we configured Trino to support TLS and connected from both Power BI Desktop and Service via HTTPS. Patrick

**Comment by fcollin** [comment]
Can you describe a little bit more the procedure you made to achieve this  please ?

**Comment by pichlerpa** [comment]
I followed [this](https://trino.io/docs/current/security/password-file.html) official Trino instruction and then just used the HTTPS endpoint for connecting.

**Comment by bvialmcs** [comment]
> Hi,
> 
> You are right, HTTP or HTTPS is automatically added to the host name based on the authentication type used in the Power BI connector. HTTP is used for anonymous (implicit) authentication, while HTTPS is used for all other types, aligning with Trino security standards.
> 
> However, the connector has not been used with LDAP, which would be the [Windows] (https://learn.microsoft.com/en-us/power-query/handling-authentication#authentication-kinds) authentication type in Power BI Custom Connectors. Currently, it only supports Basic (UsernamePassword) and Organizational account (OAuth) authentication types.
> 
> Regards, Patrick

LDAP does actually work fine. If Trino is configured to do LDAP auth, then just passing username password works fine.

**Comment by pichlerpa** [comment]
Thanks for your feedback @bvialmcs, I will close this issue.
