### ISSUE TITLE
Using Trino Connector with PowerBI Gateway

### ISSUE THREAD

**Issue by resleal** [CreativeDataEU/PowerBITrinoConnector#24]
Is it possible to use this connector with PowerBI Gateway? I've been able to use it in my local machine but would like to run this as part of a "production" architecture.

**Comment by drktorbenschnepper** [comment]
Yes, we already use the connector via an On-Premise Gateway in our production environment. It can be installed as a custom data connector. You can find more detailed documentation here: https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors

**Comment by pichlerpa** [comment]
Thanks @drktorbenschnepper for answering, I will close it.
