### ISSUE TITLE
Authentication Details 

### ISSUE THREAD

**Issue by 123srikan** [CreativeDataEU/PowerBITrinoConnector#26]
can you please share details about how to provide and configure authentication this connector

**Comment by pichlerpa** [comment]
could you please be more specific? Which authentication type do you want to use, username/password or OAuth2? What's the problem you are facing?

**Comment by 123srikan** [comment]
Thanks for quick response.
i want to use username/password for authentication. Also is it possible to restrict collection and only show specific collection.as i don't want end user to see other collections from mongo db 
![image](https://github.com/user-attachments/assets/34e019f9-7bc2-4f98-8162-f84fda586b03)

**Comment by pichlerpa** [comment]
You can apply [OLS](https://learn.microsoft.com/en-us/fabric/security/service-admin-object-level-security?tabs=table) in Power BI. Is this what you are looking for? Otherwise, please explain your use-case a little further.

**Comment by 123srikan** [comment]
My mongodb database is used by other user for generating reports in PowerBI. this user will use Powerbi .i have shared this connector details so that he can use this mongo db data in this PowerBI app . I dont want user to see other  secured data which is not useful to him.is it possible to enable authentication in connector and also restrict user to see only specific collection. since my database is used by other user  he can still see other collection

**Comment by pichlerpa** [comment]
I try to summarize:

- For report viewers: You can manage access control directly within Power BI to restrict what data they can see.
- For report authors: They access the data source directly using the credentials provided, with no alternative workaround. However, you could create multiple Trino users and set up access controls in Trino to limit data access accordingly.

I hope this answers your question.

**Comment by 123srikan** [comment]
thank you very much for quick response. 
For report viewers: You can manage access control directly within Power BI to restrict what data they can see.
**My comments**:yes  this be will taken care by PowerBI developers
For report authors: They access the data source directly using the credentials provided, with no alternative workaround. However, you could create multiple Trino users and set up access controls in Trino to limit data access accordingly.
**my comments:** This i have to check .How will restrict my data to see only limited data. Will check and let you know in case of any queries

**Comment by pichlerpa** [comment]
This might be what you are looking for: https://trino.io/docs/current/security/file-system-access-control.html

I will close this issue as it's not directly related to the connector.
