### ISSUE TITLE
Gateway options not reflecting in semantic model in power bi service when we create a dashboard using trino custom connector

### ISSUE THREAD

**Issue by nlijin** [CreativeDataEU/PowerBITrinoConnector#27]
We have a trino data source and need to create a power bi dashboard using the same.
Since power bi does not  have a built in trino connector, we used this custom connector and were able to connect to trino data source.
We created a dashboard using trino data and published it to power bi service
Now we are not able to see any gateway options for this dashboard in power bi service .

Things we tried:
We referred to below mentioned page and enabled the checkbox "On the gateway settings page in the Power BI service, select the option to enable using custom connectors with this cluster"
Even after enabling custom connector options we are not able to see MyCustomConnectors option.
[https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors]

I am not even getting an option which says **"gateway and cloud connections"** to enable gateway settings.
can you please help letting us know what could be the possible issue or help fixing this.

<img width="411" alt="gateway screenshot" src="https://github.com/user-attachments/assets/ef55256a-dd47-4913-a5ca-ff4b4c53df86">
![image](https://github.com/user-attachments/assets/e56b0932-4d72-419b-ba87-a770ce489359)

**Comment by pichlerpa** [comment]
Did you install the on-premises gateway on your local machine/server? If so, were you able to see the Trino custom connector in the list? Do you have the required permissions in the Power BI service such as tenant or gateway admin?

**Comment by nlijin** [comment]
we installed in a AWS EC2 Instance.

we installed gateway using a powershell script, and could not use the gateway exe file due to firewall restrictions.

we were not able to see the trino connector in Power bi desktop, so we added trino connector mez file to our local machine and now we are able to see the trino connector option.

No, we do not have Admin access.

Attaching the error screenshot, when we try to refresh in PBI service

<img width="499" alt="refresh error" src="https://github.com/user-attachments/assets/9449a811-edde-4124-a96d-abc2ccc4df40">

**Comment by pichlerpa** [comment]
You must configure the gateway in the power bi service. For this, it requires the required permission or it should also work if you are using the gateway personal-mode and it runs under your credentials.

**Comment by nlijin** [comment]
we already have a gateway configured in standard mode, we are able to refresh data connected with AWS redshift DB and able to find gateway options there. but we are not able to find any gateway options with datasources connected via Trino

![nogateway](https://github.com/user-attachments/assets/dfba6787-2cb8-43b0-ab34-1846279b23c3)

<img width="445" alt="withGateway" src="https://github.com/user-attachments/assets/d56c3992-a499-49ee-99ee-d2a26253322f">

**Comment by nlijin** [comment]
In the above screenshot, one with no gateway options available is the datasource connected via Trino
second one with gateway options are connected via Redshift

**Comment by pichlerpa** [comment]
I suppose the custom connector is not recognized by the on-premises gateway installed on the AWS EC2 Instance, that's why it's not configurable. Make sure the connector is placed in the right folder and the user running the on-premises gateway has access rights. Try restarting the gateway.

**Comment by nlijin** [comment]
we added the trino .mez file in my local machine inside of power bi desktop as mentioned in the readme file of the connector.
Are you suggesting if we need to add the .mez file in the EC2 Instance where we installed the gateway as well?
we have already restarted the EC2 instances, which should restart the gateway as well

<img width="785" alt="Screenshot 2024-09-10 at 6 56 39 PM" src="https://github.com/user-attachments/assets/c27248ac-733b-4ce0-b1d8-77e6164484f0">

**Comment by pichlerpa** [comment]
Yes, you need the .mez file on the machine hosting or running Trino, otherwise Power BI Service won't be able to access the data once the report is published. Additionally, I recommend not exposing the entire instance to the public, as it appears to be the case currently since you are able to connect from your local machine (Power BI Desktop), you could also design reports from within Power BI service to enhance security.

**Comment by pichlerpa** [comment]
Closed due to inactivity.
