### ISSUE TITLE
Use of the connector in Power BI Service

### ISSUE THREAD

**Issue by manudiv16** [CreativeDataEU/PowerBITrinoConnector#30]
We're trying to integrate this connector in Power BI Service. So far we've managed to add the connection to Power BI, but we don't have any data source that allows us to link it. It would be helpful if there's some documentation on how to make this integration or knowing if it's even possible with Power BI Service

Thanks in advance and good work!

**Comment by pichlerpa** [comment]
There is already a [section](https://github.com/CreativeDataEU/PowerBITrinoConnector?tab=readme-ov-file#usage-power-bi-service) on how to use it within the Power BI Service. Since the process is the same for all Power BI custom connectors, it links directly to the official Microsoft documentation. Let us know, if you need further support.

**Comment by manudiv16** [comment]
As I said, we're not having trouble configuring the connector
![image](https://github.com/user-attachments/assets/6f99dd9a-b724-4998-b379-81cef9221338)
we are struggling when it comes to managing connections or on get-data part 
![image](https://github.com/user-attachments/assets/633d0360-8f2d-45d4-abca-36ad0c586f32)
![image](https://github.com/user-attachments/assets/e39eb285-a05a-4152-81d5-363127ec8dc7)
We can only see the Azure HDInsight data source

**Comment by pichlerpa** [comment]
Once you publish a report having the custom Trino connector as a data source, you can edit the connection details in the dataset (semantic model) settings. If you are looking for a way to share the custom connector with other users to be used in the Power BI Service web experience, then this might not be possible with un-certified connectors.

**Comment by pichlerpa** [comment]
Close due to inactivity.
