### ISSUE TITLE
Trino Authentication PowerBI

### ISSUE THREAD

**Issue by SrikanthNallela** [CreativeDataEU/PowerBITrinoConnector#31]
I have set up trino with username password trying to connect powerbi. my trino is loading correctly
<img width="509" alt="image" src="https://github.com/user-attachments/assets/652331bd-6f7d-47b3-bc28-c8316a922728">
https://username:pwd@url:host/mongodb/database
is this correct way to pass?

**Comment by pichlerpa** [comment]
No, you need to choose the authentication method "Basic" in Power BI Desktop or Service once published:

![image](https://github.com/user-attachments/assets/cd163738-2f26-4d68-a10d-0078716de3b5)

**Comment by SrikanthNallela** [comment]
<img width="529" alt="image" src="https://github.com/user-attachments/assets/a169efa2-c386-434b-b878-99786fa46c1b">
keep getting remot name could not resolved .my trino is up

**Comment by SrikanthNallela** [comment]
now i gave connection as below
<img width="558" alt="image" src="https://github.com/user-attachments/assets/21d471d4-78bd-40e4-930b-2f8eef576976">
selected basic authentication got this error:with user and password
![image](https://github.com/user-attachments/assets/548385ac-9dfc-417b-bb06-e07b1ee6e0ab)

**Comment by pichlerpa** [comment]
Can you open Trino in the browser under HTTPS without ignoring the security warning? Do you have your SSL certificate in your root trust store?

**Comment by SrikanthNallela** [comment]
i have added self signed in my truste 
![image](https://github.com/user-attachments/assets/7d3d7aaf-efbc-4c40-8f39-51cb9d015002)
but still sme error .this is my trino app
<img width="418" alt="image" src="https://github.com/user-attachments/assets/5f064b1e-af12-4409-bc44-94b287f49354">

**Comment by pichlerpa** [comment]
It seems like you have a problem with the configuration of the SSL certificate, is also not recognized by your browser.

**Comment by SrikanthNallela** [comment]
its  my test environment fine for me .can you please guide me t resolve this issue in power bi

**Comment by pichlerpa** [comment]
It has nothing to do with the connector, it's your SSL configuration. Once you sorted that out, the connector will work.

**Comment by pichlerpa** [comment]
You can use self-signed certificates, it's just not configured properly, you can see that in the browser "Not secure". I don't know how Superset is handling that, but maybe it's also running in an "unsecure" context that's why it's working. Remember also to just use the host name to connect, same as in the browser just without the leading "https://".

**Comment by SrikanthNallela** [comment]
added verify=false in connection in superset to handle ssl . is possible in connector

**Comment by pichlerpa** [comment]
closed due to inactivity.
