### ISSUE TITLE
Querying to trino API

### ISSUE THREAD

**Issue by victor-msa** [CreativeDataEU/PowerBITrinoConnector#7]
So far I tested the connector and it is great, kudos for taking the time and making a usefull tool.
What I have in mind, is how to use specific querys, as in a select statement, with the connector, since I am not planning on using a whole table in my projects. 
How would someone do that?

**Comment by pichlerpa** [comment]
Hey @victor-msa,

Yes, I understand your requirement, in fact, there even is a built-in way of providing such a custom SQL statement, but it only works for ODBC connector: https://learn.microsoft.com/en-us/power-query/native-query-sdk

However, I guess it would also be possible to add this functionality somehow else by just providing a new custom field of type text. Apart from that, you could also provide a new view on the Trino side which wouldn’t require any adjustments in the connector. 

Regards,
Patrick

**Comment by pichlerpa** [comment]
@victor-msa I just updated the connector, it now supports native SQL queries.
